=== idueppe/jaxb-course-examples/solutions/xml-schema/src/main/resources/xsd/kurs-qualified.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://www.crowdcode.de/schema/kurs" 
	targetNamespace="http://www.crowdcode.de/schema/kurs"
	elementFormDefault="unqualified"
	attributeFormDefault="unqualified">
	<xs:element name="Kurs" type="tns:KursType" />
	<xs:element name="Modul" type="tns:ModulType" />
	
	<xs:complexType name="KursType">
		<xs:sequence>
			<xs:element name="Titel" type="xs:string" />
			<xs:element name="Modul" type="tns:ModulType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ModulType">
		<xs:sequence>
			<xs:element name="Ueberschrift" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="Typ" type="tns:TypeType" />
	</xs:complexType>
	
	<xs:simpleType name="TypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="notwendig"/>
			<xs:enumeration value="optional"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="zahlList">
		<xs:list itemType="xs:int" />
	</xs:simpleType>


</xs:schema>

=== idueppe/jaxb-course-examples/solutions/xml-schema/src/main/resources/xml/kurs-qualified.xml
<?xml version="1.0" ?>
<course:Kurs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:course="http://www.crowdcode.de/schema/kurs"
	xsi:schemaLocation="http://www.crowdcode.de/schema/kurs ../xsd/kurs-qualified.xsd">
	<Titel>Java Swing</Titel>
	<Modul Typ="notwendig">
		<Ueberschrift>Einleitung</Ueberschrift>
	</Modul>
	<Modul Typ="notwendig">
		<Ueberschrift>Standardkomponenten</Ueberschrift>
	</Modul>
	<Modul Typ="optional" >
		<Ueberschrift>Java2D</Ueberschrift>
	</Modul>
</course:Kurs>
