=== idueppe/jaxb-course-examples/solutions/xml-schema/src/main/resources/xsd/kurs-namespace.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:course="http://www.crowdcode.de/kurs"
    targetNamespace="http://www.crowdcode.de/kurs">
	<xs:complexType name="KursType">
		<xs:sequence>
			<xs:element name="Titel" type="xs:string"/>
			<xs:element name="Modul" type="course:ModulType" maxOccurs="unbounded"/>
            <xs:element name="Jahre">
                <xs:simpleType>
                    <xs:list itemType="xs:integer"></xs:list>
                </xs:simpleType>
            </xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ModulType">
		<xs:sequence>
			<xs:element name="Ueberschrift" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="Typ" type="xs:string"/>
	</xs:complexType>
	<xs:element name="Kurs" type="course:KursType"/>
</xs:schema>

=== idueppe/jaxb-course-examples/solutions/xml-schema/src/main/resources/xml/kurs-namespace.xml
<?xml version="1.0"?>
<course:Kurs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:course="http://www.crowdcode.de/kurs"
      xsi:schemaLocation="http://www.crowdcode.de/kurs ../xsd/kurs-namespace.xsd">
    <Titel>Java Swing</Titel>
	<Modul Typ="notwendig">
		<Ueberschrift>Einleitung</Ueberschrift>
	</Modul>
	<Modul Typ="notwendig" >
		<Ueberschrift>Standardkomponenten</Ueberschrift>
	</Modul>
	<Modul Typ="optional">
		<Ueberschrift>Java2D</Ueberschrift>
	</Modul>
	<Jahre>2005 2006 2007 2008</Jahre>
</course:Kurs>
